### ISSUE TITLE
Add favourite place

### ISSUE THREAD

**Issue by rednaks** [hatemzidi/traffc#2]
Steps to reproduce : 
1. Click on "Add fav." button
2. Click again after the first flag appear

Actual result :
- A second flag appear

Expected result : 
- Remove the current flag

This is what I expected at first, and how I see the UX, but you maybe thinking of something else.
For eg we could keep the second flag, if a user want to add more that a place at once.
But it still buggy, if you try to remove any flag, the second will be remove, but not the first one, you can't even edit the name of the place.
If you click "N-times" on the "Add Fav." Button it will keep the  N-1 flags :/ 

So, we have to decide : 
1. keep the current behaviour (add more that one marker at once) and fix the bugs.
2. Allow 1 marker at a time, and fav button will toggle current marker.

What do you think ?

EDIT : Note that all the marker are in a zombie state, you can't delete nor edit them.

**Comment by hatemzidi** [comment]
@rednaks  indeed this is a bug

for the moment, I'll continue with the idea of allowing one marker at a time (suggestion 2) :
1- the UX is much simpler as the "add Fav." is related to add one place at a time
2- the user will 'focus' on one place.
3- for technical constraints as I have some struggles with the markers' infoWindow for the moment and specially adding/editing/deleting multiple "fav" markers at the same time (but I'm starting refactoring the code keeping this in mind)

thank you.

**Comment by hatemzidi** [comment]
fixed :)
