### ISSUE TITLE
Run the app from browser

### ISSUE THREAD

**Issue by ernesst** [hatemzidi/traffc#4]
Hello, 

Is this app can be run locally from a browser or need to be behind a server ? 

When i launch http-server and connect locally to http://127.0.0.1:8080, it works. 
When i try to load files:///traffc/app/index.html, the maps isn't loaded. 

Is this an expected behavior ? 

Thanks.

**Comment by hatemzidi** [comment]
@ernesst you always need a web server.
this is expected.
